- name: prepare kube-controller-manager csr
  template: src=kube-controller-manager-csr.json.j2 dest={{ cluster_dir }}/ssl/kube-controller-manager-csr.json

- name: create kube-controller-manager cert and private key
  shell: "cd {{ cluster_dir }}/ssl && {{ base_dir }}/extra-bin/cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes kube-controller-manager-csr.json | {{ base_dir }}/extra-bin/cfssljson -bare kube-controller-manager"

- name: set cluster params
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{ cluster_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ cluster_dir }}/kube-controller-manager.kubeconfig"

- name: set client credential params
  shell: "kubectl config set-credentials system:kube-controller-manager \
        --client-certificate={{ cluster_dir }}/ssl/kube-controller-manager.pem \
        --client-key={{ cluster_dir }}/ssl/kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig={{ cluster_dir }}/kube-controller-manager.kubeconfig"

- name: set context params
  shell: "kubectl config set-context default \
        --cluster=kubernetes \
        --user=system:kube-controller-manager \
        --kubeconfig={{ cluster_dir }}/kube-controller-manager.kubeconfig"

- name: choose default context
  shell: "kubectl config use-context default \
   --kubeconfig={{ cluster_dir }}/kube-controller-manager.kubeconfig"
