- name: prepare kube-proxy csr
  template: src=kube-proxy-csr.json.j2 dest={{ cluster_dir }}/ssl/kube-proxy-csr.json

- name: create kube-proxy cert and private key
  shell: "cd {{ cluster_dir }}/ssl && {{ base_dir }}/extra-bin/cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes kube-proxy-csr.json | {{ base_dir }}/extra-bin/cfssljson -bare kube-proxy"

- name: set cluster params
  shell: "kubectl config set-cluster kubernetes \
        --certificate-authority={{ cluster_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ cluster_dir }}/kube-proxy.kubeconfig"

- name: set client credential params
  shell: "kubectl config set-credentials kube-proxy \
        --client-certificate={{ cluster_dir }}/ssl/kube-proxy.pem \
        --client-key={{ cluster_dir }}/ssl/kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig={{ cluster_dir }}/kube-proxy.kubeconfig"

- name: set context params
  shell: "kubectl config set-context default \
        --cluster=kubernetes \
        --user=kube-proxy \
        --kubeconfig={{ cluster_dir }}/kube-proxy.kubeconfig"

- name: choose default context
  shell: "kubectl config use-context default \
   --kubeconfig={{ cluster_dir }}/kube-proxy.kubeconfig"
