# Configure NTP Server
# Note: Clock synchronization across cluster nodes is mandatory
ntp_servers:
  - "ntp1.aliyun.com"
  - "time1.cloud.tencent.com"
  - "0.cn.pool.ntp.org"

# Set the network segment allowed for internal time synchronization, e.g. "10.0.0.0/8" (default: allow all)
local_network: "0.0.0.0/0"
