# https://docs.cilium.io/en/stable/installation/k8s-install-helm/#k8s-install-helm
- name: revise kernel version with float type
  set_fact:
     KERNEL_VER: "{{ ansible_kernel.split('-')[0].split('.')[0]|int + ansible_kernel.split('-')[0].split('.')[1]|int/100 }}"

- name: check if kernel version > 4.9
  fail: msg="kernel {{ ansible_kernel }} is too old for cilium installing"
  when: "KERNEL_VER|float <= 4.09"

- block:
    - name: create cilium chart setting
      template: src=values.yaml.j2 dest={{ cluster_dir }}/yml/cilium-values.yaml

    - name: helm delete cilium {{ cilium_ver }}
      shell: "{{ base_dir }}/extra-bin/helm delete cilium -n kube-system || echo true; sleep 3"
      tags: force_change_certs
      when: 'CHANGE_CA|bool'

    - name: helm create cilium {{ cilium_ver }}
      shell: "{{ base_dir }}/extra-bin/helm upgrade cilium --install \
              -n kube-system -f {{ cluster_dir }}/yml/cilium-values.yaml \
              {{ base_dir }}/roles/cilium/files/cilium-{{ cilium_ver }}.tgz"
      tags: force_change_certs
  run_once: true
  connection: local  

- name: download client tools
  copy: src={{ base_dir }}/extra-bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cilium
  - hubble

# delete original cni configurations
- name: delete default cni configurations
  file: path=/etc/cni/net.d/10-default.conf state=absent

- name: wait for cilium-node running in a polling manner
  shell: "kubectl get pod -n kube-system -owide -lk8s-app=cilium|grep ' {{ K8S_NODENAME }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 15
  delay: 8
  ignore_errors: true
  connection: local
  tags: force_change_certs

# hubble-relay may need to be restarted
- name: restart hubble-relay pod
  shell: "kubectl -n kube-system scale deploy hubble-relay --replicas=0 && sleep 5 && \
            kubectl -n kube-system scale deploy hubble-relay --replicas=1"
  run_once: true
  connection: local
  when: "cilium_hubble_enabled|bool"
  tags: force_change_certs
