# install basic system software
- name: update apt
  apt: update_cache=yes cache_valid_time=72000
  ignore_errors: true

# delete default software
- name: delete ubuntu default software
  package:
    name:
      - ufw
      - lxd
      - lxcfs
      - lxc-common
    state: absent
  ignore_errors: true

# install basic system software
- name: install ubuntu/debian basic software
  package: 
    name:
      - bash-completion     # bash completion
      - conntrack           # Connection Tracking
      - ipset               # ipvs mode
      - ipvsadm             # ipvs mode
      - jq                  # light JSON handler, docker commands need it
      - libseccomp2         # containerd requires it
      - nfs-common          # nfs function needs it
      - psmisc              # provides killall command, keepalive monitor scripts need it
      - rsync               # sync file
      - socat               # port forwarding requires it
    state: present

# optimize journal configuration, avoid wasting resource
- name: create journal relative directory
  file: name={{ item }} state=directory
  with_items:
  - "/etc/systemd/journald.conf.d"
  - "/var/log/journal"

- name: optimize journal params
  template: src=95-k8s-journald.conf.j2 dest=/etc/systemd/journald.conf.d/95-k8s-journald.conf

- name: restart journald service
  service: name=systemd-journald state=restarted
