- name: delete centos/redhat default software
  package:
    name:
      - firewalld
      - python-firewall
      - firewalld-filesystem
    state: absent
  ignore_errors: true

- name: install basic system software
  package: 
    name:
      - bash-completion     # bash completion
      - conntrack-tools     # ipvs requires
      - ipset               # ipvs requires
      - ipvsadm             # ipvs requires
      - libseccomp          # containerd requires
      - nfs-utils           # nfs function requires
      - psmisc              # psmisc provides killall command，keepalive monitoring script requires
      - rsync               # sync file
      - socat               # port forwarding requires
      - rsyslog             # rockylinux has no rsyslog service by default
    state: present

- name: disable selinux right now
  shell: "setenforce 0"
  failed_when: false

- name: disable selinux forever
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

# optimize journal configuration, avoid wasting resource
- name: forbidden rsyslog fetch journald 1, avoid double handling logs and wasting disk space
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'ModLoad imjournal'
    line: '#$ModLoad imjournal # provides access to the systemd journal'
  ignore_errors: true

- name: forbidden rsyslog fetch journald 2, avoid double handling logs and wasting disk space
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: 'IMJournalStateFile'
    line: '#$IMJournalStateFile imjournal.state'
  ignore_errors: true

- name: restart rsyslog service
  service: name=rsyslog state=restarted
  ignore_errors: true
