- name: install basic system software
  package: 
    name:
      - bash-completion     # bash completion
      - conntrack-tools     # ipvs requires
      - ipset               # ipvs requires
      - ipvsadm             # ipvs requires
      - libseccomp2         # containerd requires
      - nfs-client          # nfs requires
      - psmisc              # psmisc provides killall command，keepalive monitoring script requires
      - rsync               # sync file
      - socat               # port forwarding requires
    state: present
