- name: copy huawei cloud zypper mirror script
  copy: src=huawei-mirror-suse.sh dest=/tmp/huawei-mirror-suse.sh mode=0755

- name: apply huawei cloud zypper mirror
  shell: /tmp/huawei-mirror-suse.sh
  changed_when: false

- name: install basic system software
  package: 
    name:
      - bash-completion     # bash completion
      - conntrack-tools     # ipvs requires
      - ipset               # ipvs requires
      - ipvsadm             # ipvs requires
      - libseccomp2         # containerd requires
      - lvm2                # Local PV LVM requires
      - nfs-client          # nfs requires
      - psmisc              # psmisc provides killall command，keepalive monitoring script requires
      - rsync               # sync file
      - socat               # port forwarding requires
    state: present
