# 
- import_tasks: clean_etcd.yml
  when: 'DEL_ETCD == "yes"'

- import_tasks: clean_master.yml
  when: 'DEL_MASTER == "yes"'

- import_tasks: clean_node.yml
  when: 'DEL_NODE == "yes"'

- import_tasks: clean_lb.yml
  when: 'DEL_LB == "yes"'

- import_tasks: clean_chrony.yml
  when: 'DEL_CHRONY == "yes"'

- name: clean 'ENV PATH'
  lineinfile:
    dest: ~/.bashrc
    state: absent
    regexp: '{{ item }}'
  with_items:
  - 'kubeauto'
  - 'helm completion'
  - 'kubectl completion'
  - 'crictl completion'
  - 'HELM_TLS_ENABLE'
  when: 'DEL_ENV == "yes"'

- name: delete k8s_nodename in each node /etc/hosts
  blockinfile:
    path: /etc/hosts
    state: absent
    marker: "#### {mark} k8s node hosts ####"

  #- name: remove binaries
  #  file: name={{ item }} state=absent
  #  with_items:
  #  - "/opt/kube/bin"
  #  when: 'DEL_ETCD == "yes" and DEL_NODE == "yes" and DEL_MASTER == "yes"'

- name: important indicates WARNNING
  debug:
    msg: "[IMPORTANT]: please reboot nodes, makesure to clean out net interfaces, routes and iptables/ipvs rules."
  when: 'DEL_ETCD == "yes" and DEL_NODE == "yes" and DEL_MASTER == "yes"'
