- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "/etc/kube-lb/sbin"
  - "/etc/kube-lb/logs"
  - "/etc/kube-lb/conf"

- name: download kube-lb(nginx)
  copy: src={{ base_dir }}/extra-bin/nginx dest=/etc/kube-lb/sbin/kube-lb mode=0755

- name: create kube-lb configuration file
  template: src=kube-lb.conf.j2 dest=/etc/kube-lb/conf/kube-lb.conf
  tags: restart_kube-lb

- name: create kube-lb systemd unit file
  template: src=kube-lb.service.j2 dest=/etc/systemd/system/kube-lb.service
  tags: restart_kube-lb

- name: enable kube-lb service on startup
  shell: systemctl enable kube-lb
  ignore_errors: true

- name: start kube-lb service
  shell: systemctl daemon-reload && systemctl restart kube-lb
  ignore_errors: true
  tags: restart_kube-lb

- name: wait for kube-lb service running
  shell: "systemctl is-active kube-lb.service"
  register: svc_status
  until: '"active" in svc_status.stdout'
  retries: 3
  delay: 3
  tags: restart_kube-lb
