############################
# prepare
############################

# [optional] this option comes from project https://github.com/dev-sec/ansible-collection-hardening
# [caution] we didn't adapt this project to kubeauto
OS_HARDEN: false


############################
# role:deploy
############################
# default: ca will expire in 100 years
# default: certs issued by the ca will expire in 50 years
CA_EXPIRY: "876000h"
CERT_EXPIRY: "438000h"

# force to recreate CA and other certs, not suggested to set 'true'
CHANGE_CA: false

# kubeconfig params
CLUSTER_NAME: "cluster1"
CONTEXT_NAME: "context-{{ CLUSTER_NAME }}"

# k8s version
K8S_VER: "__k8s_ver__"

# set unique 'k8s_nodename' for each node, if not set(default:'') ip add will be used
# CAUTION: 'k8s_nodename' must consist of lower case alphanumeric characters, '-' or '.',
# and must start and end with an alphanumeric character (e.g. 'example.com'),
# regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
K8S_NODENAME: "{%- if k8s_nodename != '' -%} \
                    {{ k8s_nodename|replace('_', '-')|lower }} \
               {%- else -%} \
                    k8s-{{ inventory_hostname|replace('.', '-') }} \
               {%- endif -%}"

# use 'K8S_NODENAME' to set hostname
ENABLE_SETTING_HOSTNAME: true


############################
# role:etcd
############################
# We recommend using a separate disk for the WAL to avoid I/O contention.
ETCD_DATA_DIR: "/var/lib/etcd"
ETCD_WAL_DIR: ""


############################
# role:runtime [containerd,docker]
############################
# [.]enable accelerated registry
ENABLE_MIRROR_REGISTRY: true

# [.]enable trusting private registry
# obey the following format，'http://' and 'https://' requested
INSECURE_REG:
  - "http://registry.talkschool.cn:5000"
  - "https://reg.yourcompany.com"

# [.]basic pod image
SANDBOX_IMAGE: "registry.talkschool.cn:5000/brinnatt/pause:__pause__"

# [containerd] container layer storage
CONTAINERD_STORAGE_DIR: "/var/lib/containerd"

# [docker] container layer storage
DOCKER_STORAGE_DIR: "/var/lib/docker"

# [docker] enable Restful API
DOCKER_ENABLE_REMOTE_API: false


############################
# role:kube-master
############################
# k8s cluster certificate configuration for master，more ip and FQDN recommended
MASTER_CERT_HOSTS:
  - "122.8.8.8"
  - "k8s.brinnatt.com"


# k8s pod netmask length, which determines the maximum number of Pod IP addresses that can be allocated to each node.
# When Flannel runs in kube-subnet-mgr mode (via the --kube-subnet-mgr argument), it will allocate a Pod CIDR to each node based on that configuration.
# https://github.com/coreos/flannel/issues/847
NODE_CIDR_LEN: 24

# 是否启用集群audit功能
ENABLE_CLUSTER_AUDIT: false

############################
# role:kube-node
############################
# Kubelet root directory
KUBELET_ROOT_DIR: "/var/lib/kubelet"

# Maximum number of pods per node
MAX_PODS: 110

# Configures the amount of resources reserved for Kube components (kubelet, kube-proxy, dockerd, etc.)
# For specific value settings, refer to templates/kubelet-config.yaml.j2
KUBE_RESERVED_ENABLED: "no"

# Kubernetes does not recommend enabling system-reserved without careful consideration. It should only be configured after establishing a baseline resource usage profile through long-term monitoring.
# Additionally, the reserved amount may need to be increased over time as system workloads evolve. For specific value settings, refer to templates/kubelet-config.yaml.j2.
# The current system reservation settings are based on a minimal OS installation on a 4-core/8GB virtual machine. If using high-performance physical servers, the reservations should be increased appropriately.
# Important Note: During cluster installation, components like the API server may experience temporary high resource usage. It is advised to reserve at least 1GB of memory to accommodate this.
SYS_RESERVED_ENABLED: "no"


############################
# role:network [flannel,calico,cilium,kube-ovn,kube-router]
############################
# ------------------- flannel begin -------------------
# [flannel] flannel backend "host-gw","vxlan" can be configured
FLANNEL_BACKEND: "vxlan"
DIRECT_ROUTING: false
flannel_ver: "__flannel__"
# ------------------- flannel end ---------------------


# ------------------- calico begin --------------------
# The mode options are: [Always, CrossSubnet, Never]. Cross-subnet configurations can be set to either Always or CrossSubnet.
# CrossSubnet is a hybrid mode (tunnel + BGP routing) that enhances network performance. For nodes within the same subnet, set it to Never.
# For public cloud environments, using Always is recommended for simplicity. For other setups, adjustments to the respective cloud network configurations are required. Refer to the specific public cloud provider's documentation for details.
CALICO_ENABLE_OVERLAY: "Always"

# This setting specifies the host IP used by the calico-node. BGP neighbors establish connections using this address, which can be manually configured or auto-detected.
IP_AUTODETECTION_METHOD: "can-reach={{ groups['kube_master'][0] }}"

# Configures the Calico networking backend. Options: bird, vxlan, none.
# For certain public clouds (e.g., Azure) or private clouds that do not support IP-in-IP encapsulation, vxlan mode can be used.
CALICO_NETWORKING_BACKEND: "bird"

# Determines whether Calico uses Route Reflectors.
# It is recommended to enable this feature if the cluster scale exceeds 50 nodes.
CALICO_RR_ENABLED: false

# CALICO_RR_NODES configures the nodes to serve as Route Reflectors. If not set, cluster master nodes are used by default.
# Example: CALICO_RR_NODES: ["192.168.1.1", "192.168.1.2"]
CALICO_RR_NODES: []

# support calico versions: ["3.19", "3.23"]
calico_ver: "__calico__"

# calico main version
calico_ver_main: "{{ calico_ver.split('.')[0] }}.{{ calico_ver.split('.')[1] }}"
# ------------------- calico end -------------------


# ------------------- cilium begin -----------------
cilium_ver: "__cilium__"
cilium_connectivity_check: false
cilium_hubble_enabled: false
cilium_hubble_ui_enabled: false
# ------------------- cilium end -------------------


# ------------------- kube-ovn begin ---------------
# offline kube-ovn image tar
kube_ovn_ver: "__kube_ovn__"
# ------------------- kube-ovn end -----------------


# ------------------- kube-router begin ------------
# Due to restrictions on public clouds, IP-in-IP must generally remain Always enabled. In self-managed environments, it can be set to "subnet".
OVERLAY_TYPE: "full"
# Enables or disables NetworkPolicy support.
FIREWALL_ENABLE: true
# kube-router image version
kube_router_ver: "__kube_router__"
# ------------------- kube-router end --------------


############################
# role:cluster-addon
############################
# coredns installed by default
dns_install: "yes"
corednsVer: "__coredns__"
ENABLE_LOCAL_DNS_CACHE: true
dnsNodeCacheVer: "__dns_node_cache__"
# set local dns cache address
LOCAL_DNS_CACHE: "169.254.20.10"


# metric server installed by default
metricsserver_install: "yes"
metricsVer: "__metrics__"


# dashboard not installed by default
dashboard_install: "no"
dashboardVer: "__dashboard__"


# local-storage (local-path-provisioner) not installed by default
local_path_provisioner_install: "no"
local_path_provisioner_ver: "__local_path_provisioner__"
local_path_storage_class: "local-path"
# Set the path for local persistent volumes
local_path_provisioner_dir: "/opt/local-path-provisioner"


# nfs-provisioner not installed by default
nfs_provisioner_install: "no"
nfs_provisioner_namespace: "kube-system"
nfs_provisioner_ver: "__nfs_provisioner__"
nfs_storage_class: "managed-nfs-storage"
nfs_server: "192.168.1.10"
nfs_path: "/data/nfs"


# openebs not installed by default
openebs_install: "no"
openebs_ver: "__openebs_ver__"
openebs_namespace: "openebs"
openebs_hostpath: "/var/openebs/local"
openebs_hostpath_storage_class: "openebs-hostpath"
openebs_lvm_storage_class: "openebs-lvmpv"
openebs_lvm_vg: "vg_k8s"


# prometheus not installed by default
prom_install: "no"
prom_namespace: "monitor"
prom_storage_class: ""
prom_chart_ver: "__prom_chart__"


# minio not installed by default
minio_install: "no"
minio_namespace: "minio"
minio_storage_class: "{{ openebs_lvm_storage_class }}"
minio_chart_ver: "__minio_chart__"
minio_root_user: "3aea61ca94177dx"
minio_root_password: "0f3b19e46dd3aea61ca94177d"
# single=1，cluster>=4
minio_pool_servers: 4
minio_pool_size: 10Gi
# Controls whether TLS certificates are enabled. If disabled, the HTTP protocol will be used instead.
minio_tls_enabled: false
# Determines whether to use an authoritative certificate. If enabled, the certificate must be placed in the directory roles/cluster-addon/templates/minio/ in advance, with the certificate and private key named server.crt and server.key, respectively.
minio_with_global_cert: false


# nacos not installed by default
nacos_install: "no"
nacos_namespace: "nacos"
nacos_mysql_host: "semisync-mysql-cluster-mysql"
nacos_mysql_db: "nacos"
nacos_mysql_port: "3306"
nacos_mysql_user: "__dbuser__"
nacos_mysql_password: "__yourpassword__"
nacos_storage_class: "{{ openebs_lvm_storage_class }}"


# rocketmq not installed by default
rocketmq_install: "no"
rocketmq_namespace: "rocketmq"
rocketmq_storage_class: "{{ openebs_lvm_storage_class }}"


# network-check not installed by default
network_check_enabled: false
network_check_schedule: "*/5 * * * *"

# kubeblocks deprecated
#kubeblocks_ver: "__kubeblocks_ver__"
#kubeblocks_install: "no"

# ingress-nginx not installed by default
# The ingress-nginx controller will run on nodes bearing the label `ingress-controller/provider=ingress-nginx`
ingress_nginx_install: "no"
ingress_nginx_namespace: "ingress-nginx"
ingress_nginx_ver: "__ingress_nginx_ver__"
ingress_nginx_metrics_enabled: true # request prometheus installed firstly


############################
# role:harbor
############################
# harbor full version
HARBOR_VER: "__harbor__"
HARBOR_DOMAIN: "harbor.brinnatt.io.local"
HARBOR_PATH: /var/data
HARBOR_TLS_PORT: 8443
HARBOR_REGISTRY: "{{ HARBOR_DOMAIN }}:{{ HARBOR_TLS_PORT }}"

# if set 'false', you need to put certs named harbor.pem and harbor-key.pem in directory 'down'
HARBOR_SELF_SIGNED_CERT: true

# install extra component
HARBOR_WITH_TRIVY: false
