# Delete kube_master related services
DEL_MASTER: "no"

# Delete kube_node related services
DEL_NODE: "no"

# Delete etcd related services
DEL_ETCD: "no"

# Delete LB related services
DEL_LB: "no"

# Delete chronyd related services
DEL_CHRONY: "no"

# Delete kubeauto envs
DEL_ENV: "yes"
