- name: configure flannel DaemonSet yaml file
  template: src=kube-flannel.yaml.j2 dest={{ cluster_dir }}/yml/flannel.yaml
  run_once: true
  connection: local

- name: delete flannel network before applying
  shell: "kubectl delete -f {{ cluster_dir }}/yml/flannel.yaml || echo true; sleep 3"
  run_once: true
  connection: local
  tags: force_change_certs
  when: 'CHANGE_CA|bool'

- name: apply flannel network
  shell: "kubectl apply -f {{ cluster_dir }}/yml/flannel.yaml"
  run_once: true
  connection: local
  tags: force_change_certs

- name: delete default cni configuration
  file: path=/etc/cni/net.d/10-default.conf state=absent

- name: wait for flannel running in a polling manner
  shell: "kubectl get pod -n kube-system -o wide|grep 'flannel'|grep ' {{ K8S_NODENAME }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 15
  delay: 8
  ignore_errors: true
  connection: local
  tags: force_change_certs
