- block:
    - name: prepare kubelet CSR
      template: src=kubelet-csr.json.j2 dest={{ cluster_dir }}/ssl/{{ K8S_NODENAME }}-kubelet-csr.json

    - name: create kubelet cert and private key
      shell: "cd {{ cluster_dir }}/ssl && {{ base_dir }}/extra-bin/cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes {{ K8S_NODENAME }}-kubelet-csr.json | {{ base_dir }}/extra-bin/cfssljson -bare {{ K8S_NODENAME }}-kubelet"

    - name: set cluster params
      shell: "kubectl config set-cluster kubernetes \
            --certificate-authority={{ cluster_dir }}/ssl/ca.pem \
            --embed-certs=true \
            --server={{ KUBE_APISERVER }} \
            --kubeconfig={{ cluster_dir }}/{{ K8S_NODENAME }}-kubelet.kubeconfig"

    - name: set client credential params
      shell: "kubectl config set-credentials system:node:{{ K8S_NODENAME }} \
            --client-certificate={{ cluster_dir }}/ssl/{{ K8S_NODENAME }}-kubelet.pem \
            --embed-certs=true \
            --client-key={{ cluster_dir }}/ssl/{{ K8S_NODENAME }}-kubelet-key.pem \
            --kubeconfig={{ cluster_dir }}/{{ K8S_NODENAME }}-kubelet.kubeconfig"

    - name: set context params
      shell: "kubectl config set-context default \
            --cluster=kubernetes \
            --user=system:node:{{ K8S_NODENAME }} \
            --kubeconfig={{ cluster_dir }}/{{ K8S_NODENAME }}-kubelet.kubeconfig"

    - name: choose default context
      shell: "kubectl config use-context default \
            --kubeconfig={{ cluster_dir }}/{{ K8S_NODENAME }}-kubelet.kubeconfig"
  connection: local

- name: distribute ca cert
  copy: src={{ cluster_dir }}/ssl/ca.pem dest={{ ca_dir }}/ca.pem

- name: distribute kubelet cert
  copy: src={{ cluster_dir }}/ssl/{{ K8S_NODENAME }}-{{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - kubelet.pem
  - kubelet-key.pem

- name: distribute kubeconfig
  copy: src={{ cluster_dir }}/{{ K8S_NODENAME }}-kubelet.kubeconfig dest=/etc/kubernetes/kubelet.kubeconfig
