- block:
    - name: prepare cilium-check configuration dirs
      file: name={{ cluster_dir }}/yml/cilium-check state=directory
    
    - name: prepare deployment file
      template: src=cilium-check/{{ item }}.j2 dest={{ cluster_dir }}/yml/cilium-check/{{ item }}
      with_items:
      - "connectivity-check.yaml"
      - "check-part1.yaml"
      - "namespace.yaml"
    
    - name: create test namespace
      shell: "kubectl apply -f {{ cluster_dir }}/yml/cilium-check/namespace.yaml"
    
    - name: create test part1
      shell: "kubectl apply -n cilium-test -f {{ cluster_dir }}/yml/cilium-check/check-part1.yaml"
    
    - name: wait for echo pod running in a polling manner
      shell: "kubectl get pod -n cilium-test |grep echo|grep Running|grep '1/1'|wc -l"
      register: pod_status
      until: pod_status.stdout == "3"
      retries: 15
      delay: 8
      ignore_errors: true
    
    - name: create integrity connectivity-check
      shell: "kubectl apply -n cilium-test -f {{ cluster_dir }}/yml/cilium-check/connectivity-check.yaml"

    - debug:
        msg: "[Important]: Please check if all pods are completed or running state in cilium-test namespace, no restarting count increment.
        That indicates the cilium connection is normal. After a period of test observation, you can delete all resources
        in cilium-test namespace."
  when: 'cilium_connectivity_check|bool'
