- block:
    - name: prepare DNS deployment file
      template: src=dns/coredns.yaml.j2 dest={{ cluster_dir }}/yml/coredns.yaml

    - name: delete coredns before applying
      shell: "kubectl delete -f {{ cluster_dir }}/yml/coredns.yaml || echo true; sleep 3"
      tags: force_change_certs
      when: 'CHANGE_CA|bool'

    - name: apply coredns
      shell: "kubectl apply -f {{ cluster_dir }}/yml/coredns.yaml"
      tags: force_change_certs
  when: 'dns_install == "yes"'
