# https://kubeblocks.io/docs/release-0.9/user_docs/installation/install-kubeblocks
- name: create kubeblocks yml dir
  file: name={{ cluster_dir }}/yml/kubeblocks state=directory

- name: create kubeblocks clusters customized settings
  template: src=kubeblocks/{{ item }}.yaml.j2 dest={{ cluster_dir }}/yml/kubeblocks/{{ item }}.yaml
  with_items:
    - kb-values
    - mysql-cluster
    - pg-cluster
    - redis-cluster
    - minio-cluster
    - es-cluster
    - mongodb-cluster

- block:
    - name: create kubeblocks crd
      shell: "kubectl create -f {{ base_dir }}/roles/cluster-addon/files/kubeblocks_crds.yaml"
      ignore_errors: true

    - name: helm create kubeblocks
      shell: "{{ base_dir }}/extra-bin/helm upgrade kubeblocks --install --create-namespace -n kb-system \
              -f {{ cluster_dir }}/yml/kubeblocks/kb-values.yaml \
              {{ base_dir }}/roles/cluster-addon/files/kubeblocks-0.9.3.tgz"
  when: '"kubeblocks-dataprotection" not in pod_info.stdout'

- name: helm create kb-addon-minio
  shell: "{{ base_dir }}/extra-bin/helm upgrade -i -n kb-system kb-addon-minio \
          --set image.registry=registry.talkschool.cn:5000 \
          {{ base_dir }}/roles/cluster-addon/files/minio-0.9.0.tgz"
  when: 'kb_addon_minio_install == "yes"'

- name: helm create kb-addon-es
  shell: "{{ base_dir }}/extra-bin/helm upgrade -i -n kb-system kb-addon-es \
          --set image.registry=registry.talkschool.cn:5000 \
          {{ base_dir }}/roles/cluster-addon/files/elasticsearch-0.9.1.tgz"
  when: 'kb_addon_es_install == "yes"'

- name: wait for deploying kb-addon-mysql chart in a polling manner
  shell: "{{ base_dir }}/extra-bin/helm ls -n kb-system|grep kb-addon-mysql|awk '{print $8}'"
  register: mysql_status
  until: mysql_status.stdout == "deployed"
  retries: 15
  delay: 5
  ignore_errors: true

- name: wait for deploying kb-addon-postgresql chart in a polling manner
  shell: "{{ base_dir }}/extra-bin/helm ls -n kb-system|grep kb-addon-postgresql|awk '{print $8}'"
  register: pg_status
  until: pg_status.stdout == "deployed"
  retries: 15
  delay: 5
  ignore_errors: true

- name: wait for depoying kb-addon-redis chart in a polling manner
  shell: "{{ base_dir }}/extra-bin/helm ls -n kb-system|grep kb-addon-redis|awk '{print $8}'"
  register: redis_status
  until: redis_status.stdout == "deployed"
  retries: 15
  delay: 5
  ignore_errors: true

- name: Set the chart to allow modification of the image address
  shell: "kubectl annotate componentdefinitions.apps.kubeblocks.io mysql-5.7 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io mysql-8.0 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io mysql-8.4 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io redis-7 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io redis-sentinel-7 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io minio apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io elasticsearch-8 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io kibana-8 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io mongodb apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io postgresql-15 apps.kubeblocks.io/skip-immutable-check=true && \
      kubectl annotate componentdefinitions.apps.kubeblocks.io postgresql-16 apps.kubeblocks.io/skip-immutable-check=true"
  ignore_errors: true

- name: helm create kb-addon-mysql
  shell: "{{ base_dir }}/extra-bin/helm upgrade -n kb-system kb-addon-mysql \
          --set image.registry=registry.talkschool.cn:5000 \
          {{ base_dir }}/roles/cluster-addon/files/mysql-0.9.1.tgz"
  when: 'kb_addon_mysql_install == "yes"'

- name: helm create kb-addon-postgresql
  shell: "{{ base_dir }}/extra-bin/helm upgrade -n kb-system kb-addon-postgresql \
          --set image.registry=registry.talkschool.cn:5000 \
          {{ base_dir }}/roles/cluster-addon/files/postgresql-0.9.0.tgz"
  when: 'kb_addon_pg_install == "yes"'

- name: helm create kb-addon-redis
  shell: "{{ base_dir }}/extra-bin/helm upgrade -n kb-system kb-addon-redis \
          --set image.registry=registry.talkschool.cn:5000 \
          {{ base_dir }}/roles/cluster-addon/files/redis-0.9.1.tgz"
  when: 'kb_addon_redis_install == "yes"'

- name: helm create kb-addon-mongodb
  shell: "{{ base_dir }}/extra-bin/helm upgrade -n kb-system kb-addon-mongodb \
          --set image.registry=registry.talkschool.cn:5000 \
          {{ base_dir }}/roles/cluster-addon/files/mongodb-0.9.1.tgz"
  when: 'kb_addon_mongodb_install == "yes"'

- name: optimize mysql node health check probe
  shell: 'kubectl patch ComponentDefinition mysql-8.0 --type merge --patch "{\"spec\":{\"lifecycleActions\":{\"roleProbe\":{\"periodSeconds\":5,\"timeoutSeconds\":2}}}}"'
  ignore_errors: true

- name: optimize postgresql node health check probe
  shell: 'kubectl patch ComponentDefinition postgresql-16 --type merge --patch "{\"spec\":{\"lifecycleActions\":{\"roleProbe\":{\"periodSeconds\":5,\"timeoutSeconds\":2}}}}"'
  ignore_errors: true
