- block:
    - name: prepare metrics-server deployment file
      template: src=metrics-server/components.yaml.j2 dest={{ cluster_dir }}/yml/metrics-server.yaml

    - name: delete metrics-server before applying
      shell: "kubectl delete -f {{ cluster_dir }}/yml/metrics-server.yaml || echo true; sleep 3"
      tags: force_change_certs
      when: 'CHANGE_CA|bool'

    - name: apply metrics-server
      shell: "kubectl apply -f {{ cluster_dir }}/yml/metrics-server.yaml"
      tags: force_change_certs
  when: 'metricsserver_install == "yes"'
