- block:
    - name: prepare network-check configuration dirs
      file: name={{ cluster_dir }}/yml/network-check state=directory
    
    - name: prepare deployment file
      template: src=network-check/{{ item }}.j2 dest={{ cluster_dir }}/yml/network-check/{{ item }}
      with_items:
      - "network-check.yaml"
      - "namespace.yaml"
    
    - name: create test namespace
      shell: "kubectl apply -f {{ cluster_dir }}/yml/network-check/namespace.yaml"
    
    - name: create complete network-check
      shell: "kubectl apply -n network-test -f {{ cluster_dir }}/yml/network-check/network-check.yaml"

    - debug:
        msg: "[Important]: Please check if all pods are completed or running state in network-test namespace, no restarting count increment.
                That indicates the network connection is normal. After a period of test observation, you can delete all resources
                in network-test namespace."
  when: "network_check_enabled|bool"
