- block:
    - name: prepare dnscache deployment file with ipvs
      template: src=dns/nodelocaldns-ipvs.yaml.j2 dest={{ cluster_dir }}/yml/nodelocaldns.yaml
      when: "PROXY_MODE == 'ipvs'"

    - name: prepare dnscache deployment file with iptables
      template: src=dns/nodelocaldns-iptables.yaml.j2 dest={{ cluster_dir }}/yml/nodelocaldns.yaml
      when: "PROXY_MODE == 'iptables'"

    - name: delete dnscache before applying
      shell: "kubectl delete -f {{ cluster_dir }}/yml/nodelocaldns.yaml || echo true; sleep 3"
      tags: force_change_certs
      when: 'CHANGE_CA|bool'

    - name: apply dnscache
      shell: "kubectl apply -f {{ cluster_dir }}/yml/nodelocaldns.yaml"
      tags: force_change_certs
  when: 'ENABLE_LOCAL_DNS_CACHE|bool'
