# Distinguish multicast VRRP groups for multiple instances. Duplicate values within the same network segment are not allowed, and the value range is 0-255.
# Since the project has already configured VRRP packets in unicast mode, duplicate ROUTER_ID values within the same network segment are acceptable.
ROUTER_ID: 222

# Enable load balancing for ingress NodePort services (yes/no)
INGRESS_NODEPORT_LB: "no"

# Port number for ingress NodePort
INGRESS_NODEPORT_LB_PORT: 23456

# Enable load balancing for ingress TLS NodePort services (yes/no)
INGRESS_TLS_NODEPORT_LB: "no"

# Port number for ingress TLS NodePort
INGRESS_TLS_NODEPORT_LB_PORT: 23457
