- block:
    - name: create calico CSR
      template: src=calico-csr.json.j2 dest={{ cluster_dir }}/ssl/calico-csr.json

    - name: create calico cert and private key
      shell: "cd {{ cluster_dir }}/ssl && {{ base_dir }}/extra-bin/cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes calico-csr.json|{{ base_dir }}/extra-bin/cfssljson -bare calico"

    - name: delete old calico-etcd-secrets
      shell: "kubectl -n kube-system delete secrets calico-etcd-secrets || echo NotFound"

    - name: create calico-etcd-secrets
      shell: "cd {{ cluster_dir }}/ssl && \
            kubectl create secret generic -n kube-system calico-etcd-secrets \
            --from-file=etcd-ca=ca.pem \
            --from-file=etcd-key=calico-key.pem \
            --from-file=etcd-cert=calico.pem"

    - name: configure calico DaemonSet yaml file
      template: src=calico-{{ calico_ver_main }}.yaml.j2 dest={{ cluster_dir }}/yml/calico.yaml

    - name: delete calico network
      shell: "kubectl delete -f {{ cluster_dir }}/yml/calico.yaml || echo NotFound; sleep 3"
      when: 'CHANGE_CA|bool'

    - name: apply calico network
      shell: "kubectl apply -f {{ cluster_dir }}/yml/calico.yaml"
  run_once: true
  connection: local
  tags: force_change_certs

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - /etc/calico/ssl

- name: distribute calico cert-related files
  copy: src={{ cluster_dir }}/ssl/{{ item }} dest=/etc/calico/ssl/{{ item }}
  with_items:
  - ca.pem
  - calico.pem
  - calico-key.pem
  tags: force_change_certs

- name: delete default cni configuration
  file: path=/etc/cni/net.d/10-default.conf state=absent

- name: download calicoctl client command
  copy: src={{ base_dir }}/extra-bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - calicoctl
  ignore_errors: true

- name: prepare calicoctl configuration file
  template: src=calicoctl.cfg.j2 dest=/etc/calico/calicoctl.cfg

- name: wait for calico-node running in a polling manner
  shell: "kubectl get pod -n kube-system -o wide|grep 'calico-node'|grep ' {{ K8S_NODENAME }} '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 15
  delay: 15
  ignore_errors: true
  connection: local
  tags: force_change_certs

- import_tasks: calico-rr.yml
  when: 'CALICO_RR_ENABLED|bool'
  tags: force_change_certs
