# etcd cluster IP:PORT generated according to all members
TMP_NODES: "{% for h in groups['etcd'] %}etcd-{{ h }}=https://{{ h }}:2380,{% endfor %}"
ETCD_NODES: "{{ TMP_NODES.rstrip(',') }}"

# etcd cluster initial state new/existing
CLUSTER_STATE: "new"
