- name: check if docker was installed
  shell: 'systemctl is-active docker || echo "NoFound"'
  register: docker_svc

- name: get docker version information
  shell: "{{ base_dir }}/docker-bin/dockerd --version | awk '{print $3}' | tr -d ','"
  register: docker_ver
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: debug info
  debug: var="docker_ver"
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: revise docker version with float type
  set_fact:
    DOCKER_VER: "{{ docker_ver.stdout.split('.')[0]|int + docker_ver.stdout.split('.')[1]|int/100 }}"
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: infer docker installed
  debug:
    msg: "The docker has been installed yet"
  when: "'NoFound' not in docker_svc.stdout" 

- block:
    - name: prepare docker-related directories
      file: name={{ item }} state=directory
      with_items:
      - "{{ bin_dir }}"
      - "/etc/docker"
    
    - name: download docker binary
      copy: src={{ item }} dest={{ bin_dir }}/ mode=0755
      with_fileglob:
      - "{{ base_dir }}/docker-bin/*"
      tags: upgrade_docker, download_docker
    
    - name: configure docker daemon
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json
    
    - name: create docker systemd unit file
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
      tags: upgrade_docker, download_docker
    
    - name: enable docker service on startup
      shell: systemctl enable docker
      ignore_errors: true
    
    - name: start docker service
      shell: systemctl daemon-reload && systemctl restart docker
      tags: upgrade_docker

    - name: wait for docker running
      shell: "systemctl is-active docker.service"
      register: docker_status
      until: '"active" in docker_status.stdout'
      retries: 8
      delay: 2
      tags: upgrade_docker
    
    # configure docker symlink，it's convenient to maintain
    - name: configure docker symlink
      file: src={{ bin_dir }}/docker dest=/usr/bin/docker state=link
      ignore_errors: true
  when: "'NoFound' in docker_svc.stdout"
