# WARNNING:  this playbook will clean the kube_master node {{ NODE_TO_DEL }}

- hosts: localhost
  tasks:
    - fail: msg="{{ NODE_TO_DEL }} is NOT a master node!"
      when: "NODE_TO_DEL not in groups['kube_master']"

    - fail: msg="you CAN NOT delete the last member of kube_master!"
      when: "groups['kube_master']|length < 2 and NODE_TO_DEL in groups['kube_master']"

    - name: register K8S main version variable
      shell: echo {{ K8S_VER }}|awk -F. '{print $1"."$2}'
      register: K8S_VER_MAIN

    - name: set kubectl drain params
      set_fact: DRAIN_OPT="--delete-emptydir-data --ignore-daemonsets --force"
      when: "K8S_VER_MAIN.stdout|float > 1.19"

    - name: set kubectl drain params
      set_fact: DRAIN_OPT="--delete-local-data --ignore-daemonsets --force"
      when: "K8S_VER_MAIN.stdout|float < 1.20"

    - name: debug info
      debug: var="DRAIN_OPT"

    - name: get the node name to delete
      shell: "kubectl get node -owide|grep ' {{ NODE_TO_DEL }} '|awk '{print $1}'"
      register: NODE_NAME

    - debug: var="NODE_NAME.stdout"

    - name: run kubectl drain @{{ NODE_NAME.stdout }}
      shell: "kubectl drain {{ NODE_NAME.stdout }} {{ DRAIN_OPT }}"
      #ignore_errors: true

    - name: clean master {{ NODE_TO_DEL }}
      import_role:
        name: clean
      vars:
        DEL_MASTER: yes
        DEL_NODE: yes
        DEL_ENV: yes
        DEL_LB: yes
      delegate_to: "{{ NODE_TO_DEL }}"
      register: CLEAN_STATUS

    - debug: var="CLEAN_STATUS"


- hosts:
    - kube_master
    - kube_node
  tasks:
    - name: remove the {{ NODE_TO_DEL }} entry in all k8s hosts file
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: "^{{ NODE_TO_DEL }}.* flag by kubeauto"