- name: prepare containerd-related directories
  file: name={{ item }} state=directory
  with_items:
  - "/etc/containerd"
  - "/etc/containerd/certs.d/docker.io"

- name: load kernel module overlay
  modprobe: name=overlay state=present

- name: download containerd binary
  copy: src={{ item }} dest={{ bin_dir }} mode=0755
  with_fileglob:
  - "{{ base_dir }}/extra-bin/containerd-bin/*"
  tags: upgrade

- name: download crictl
  copy: src={{ base_dir }}/extra-bin/crictl dest={{ bin_dir }}/crictl mode=0755

- name: crictl bash completion
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: 'crictl completion'
    line: 'source <(crictl completion bash) # flag by kubeauto'
  
- name: create containerd configuration file
  template: src=config.toml.j2 dest=/etc/containerd/config.toml
  tags: upgrade

- name: create systemd unit file
  template: src=containerd.service.j2 dest=/etc/systemd/system/containerd.service
  tags: upgrade

- name: create crictl configuration
  template: src=crictl.yaml.j2 dest=/etc/crictl.yaml

- name: enable containerd service on startup
  shell: systemctl enable containerd
  ignore_errors: true

- name: start containerd service
  shell: systemctl daemon-reload && systemctl restart containerd
  tags: upgrade

- name: wait for containerd service running
  shell: "systemctl is-active containerd.service"
  register: containerd_status
  until: '"active" in containerd_status.stdout'
  retries: 8
  delay: 2
  tags: upgrade
